DECLARE @LOJAS VARCHAR(MAX) = ISNULL({vw_filtros.loja},'')
DECLARE @PRODUTO VARCHAR(50) = ISNULL(LTRIM(RTRIM({vw_filtros.produto})),'')
DECLARE @SUB VARCHAR(30) = ISNULL(LTRIM(RTRIM({vw_filtros.subcategoria})),'')
DECLARE @SQL NVARCHAR(MAX)   
   
   

SET @SQL = '
	   
	SELECT 
		A.OBJETO_CONTROLE AS LOJA,
		A.PRODUTO,
		B.DESCRICAO,
		D.DESCRICAO AS SUBCATEGORIA,
		E.EAN,
		C.ESTOQUE_SALDO,
		FARMAPONTE.UDF_DEMANDA_CALCULAR(A.ESTOQUE_MAXIMO,A.ESTOQUE_MINIMO,A.ESTOQUE_LIMITADOR,A.VALIDADE_MINIMO) AS DEMANDA		
	FROM PRODUTOS_LOCAIS A 
	JOIN PRODUTOS B ON 
		B.PRODUTO = A.PRODUTO 
	JOIN ESTOQUE_ATUAL C ON 
		C.PRODUTO = A.PRODUTO AND
		C.CENTRO_ESTOQUE = A.OBJETO_CONTROLE
	JOIN SUBCATEGORIAS_PRODUTOS D WITH(NOLOCK) ON
		D.SUBCATEGORIA_PRODUTO = B.SUBCATEGORIA_PRODUTO
	JOIN farmaponte.VW_PRODUTOS_EAN E ON 
		E.PRODUTO = A.PRODUTO
	JOIN SP.UDF_SPLIT_1(''' + @LOJAS + ''', '','') F ON
		SP.UDF_IS_NUMERIC(F.ITEM) = A.OBJETO_CONTROLE
	'+
	CASE	
		WHEN LEN(@SUB) > 0
			THEN 'JOIN SP.UDF_SPLIT_1(''' + @SUB + ''', '','') G ON
					SP.UDF_IS_NUMERIC(G.ITEM) = D.SUBCATEGORIA_PRODUTO'
			ELSE ''
		END +'
	WHERE 
		1=1 '+
		CASE 
			WHEN ISNUMERIC(@PRODUTO) = 1
				THEN ' AND A.PRODUTO = SP.UDF_IS_NUMERIC('+@PRODUTO+')'
			WHEN ISNUMERIC(@PRODUTO) = 0 AND LEN(@PRODUTO) > 3
				THEN ' AND (B.DESCRICAO LIKE ''%'' + '''+@PRODUTO+''' + ''%'' OR '''+@PRODUTO+''' = '''')'
			ELSE ''
		END +'
	ORDER BY
		A.OBJETO_CONTROLE

'

EXECUTE sp_executesql @SQL