DECLARE
@MOVIMENTO DATETIME,
@SQL NVARCHAR(MAX);

SET @MOVIMENTO = '30/06/2020'

/*----------------------------------------------------------------------------------------------*/
IF OBJECT_ID('TEMPDB..#TEMPORARIA') IS NOT NULL
   DROP TABLE  #TEMPORARIA 

SELECT    	
    A.LOJA, 
    A.CAIXA, 
    FARMAPONTE.UDF_FORMATA_DATA(A.MOVIMENTO,1,'/') AS MOVIMENTO, 
    A.ABERTURA, 
    A.VENDA,
	A.ECF_CUPOM,
	A.FINALIZADORA,
	C.TOTAL_ITENS,
	B.TOTAL_FINALIZADORAS,
	A.TIPO,
	A.CODIGO_PBM,
	A.VALOR,
	A.TROCO	
INTO #TEMPORARIA
FROM PDV_FINALIZADORAS A
OUTER APPLY (
	SELECT 
		COUNT(*) as CONTADOR,
		SUM((AA.VALOR - AA.TROCO) * 
		CASE 
			WHEN AA.[STATUS] = 'A' THEN 1 
			ELSE -1 
		END ) AS TOTAL_FINALIZADORAS
	FROM PDV_FINALIZADORAS AA
	WHERE
		AA.LOJA = A.LOJA AND
		AA.CAIXA = A.CAIXA AND
		AA.MOVIMENTO = A.MOVIMENTO AND
		AA.VENDA = A.VENDA
) B	
OUTER APPLY (
	SELECT 
		SUM(((AA.PRECO - AA.DESCONTO) * AA.QUANTIDADE) * 
		CASE 
			WHEN AA.[STATUS] = 'A' THEN 1 
			ELSE -1 
		END) AS TOTAL_ITENS
	FROM PDV_ITENS AA
	WHERE
		AA.LOJA = A.LOJA AND
		AA.CAIXA = A.CAIXA AND
		AA.MOVIMENTO = A.MOVIMENTO AND
		AA.VENDA = A.VENDA 	
) C	
WHERE   
    A.MOVIMENTO = @MOVIMENTO AND
	B.TOTAL_FINALIZADORAS <> C.TOTAL_ITENS AND
	B.CONTADOR = 1 
/*GROUP BY
	A.LOJA, 
    A.CAIXA, 
    A.MOVIMENTO, 
    A.ABERTURA, 
    A.VENDA,
	A.ECF_CUPOM,
	A.FINALIZADORA,
	C.TOTAL_ITENS,
	B.TOTAL_FINALIZADORAS*/
ORDER BY
	A.LOJA,
	A.CAIXA,
	A.ECF_CUPOM


--select * from #TEMPORARIA

/*---------------------------------------------------INSERT TB_TMP_PDV_FINALIZADORAS-------------------------------------------------*/


 INSERT OPENQUERY(
        PostgreSQL05,
        'select * from desenvolvimento.tb_tmp_pdv_finalizadoras'
    )SELECT * from #TEMPORARIA
	 WHERE TIPO = 5
	   AND CODIGO_PBM = 4
	   AND TROCO = 0



/*--------------------------------------------------------UPDATE PDV_FINALIZADORAS--------------------------------------------------*/

SELECT B.TOTAL_ITENS,A.*  
--UPDATE A SET A.VALOR = B.TOTAL_ITENS
  FROM PDV_FINALIZADORAS A WITH(NOLOCK)
  JOIN #TEMPORARIA B ON B.LOJA = A.LOJA
					AND B.CAIXA = A.CAIXA
					AND B.MOVIMENTO = A.MOVIMENTO
					AND B.VENDA = A.VENDA
					AND B.FINALIZADORA = A.FINALIZADORA
 WHERE A.VALOR <> B.TOTAL_ITENS
   AND B.TIPO = 5
   AND B.CODIGO_PBM = 4
   AND B.TROCO = 0
