

select 
   convert(xml,conteudo) 
from
   nfe_fornecedores  A
where 
   A.chave_nfe = '35200617821568000176550010000015091025781786'  --'35200617821568000176550010000015101025785154'




--SELECT 'Total do ICMS Desonerado da nota ' + CAST(A.TOTAL_ICMS_DESONERADO AS VARCHAR) + 
--		' diverge do total dos produtos ' + CAST(B.TOTAL_ICMS_DESONERADO AS VARCHAR)
--FROM NF_COMPRA_TOTAIS A WITH(NOLOCK)
--OUTER APPLY (
--    SELECT
--SUM(ISNULL(BB.ICMS_VALOR_DESONERADO,0)) AS TOTAL_ICMS_DESONERADO
--FROM NF_COMPRA_PRODUTOS BB WITH(NOLOCK)
--WHERE
--BB.NF_COMPRA = 1127205
--) B
--WHERE
--    A.NF_COMPRA = 1127205 AND
--ABS(A.TOTAL_ICMS_DESONERADO - B.TOTAL_ICMS_DESONERADO) > 0

--UPDATE A SET A.TOTAL_ICMS_DESONERADO = 0
----SELECT A.TOTAL_ICMS_DESONERADO, *
-- FROM NF_COMPRA_TOTAIS A  
-- JOIN (SELECT NF_COMPRA , SUM(COALESCE(ICMS_DESONERADO,ICMS_VALOR_DESONERADO, 0)) AS ICMS_DESONERADO
--	   FROM NF_COMPRA_PRODUTOS 
--	   WHERE NF_COMPRA = 1127205 --1123751
--	   GROUP BY NF_COMPRA
--	   )B ON B.NF_COMPRA = A.NF_COMPRA
-- JOIN NF_COMPRA C WITH(NOLOCK) ON C.NF_COMPRA = A.NF_COMPRA
--WHERE A.TOTAL_ICMS_DESONERADO > 0	
--  AND C.IGNORAR_VALIDACAO = 'S' 
--  AND B.ICMS_DESONERADO = 0


