UNION ALL

SELECT TOP 1 'NOTA FISCAL JÁ CONTABILIZADA - '+CAST(A.CONTABILIDADE AS VARCHAR(20))
FROM CONTABIL_LANCAMENTOS A WITH (NOLOCK)
WHERE
	A.FORMULARIO_ORIGEM =:FORMULARIO_ORIGEM AND
	A.TAB_MASTER_ORIGEM =:TAB_MASTER_ORIGEM AND
	A.REG_MASTER_ORIGEM =:REG_MASTER_ORIGEM

----------------------------------------------------------------------

select  cl.FORMULARIO_ORIGEM,cl.tab_master_origem,cl.reg_master_origem 



SELECT TOP 1 'NOTA FISCAL JÁ CONTABILIZADA - '+ CAST(B.CONTABILIDADE AS VARCHAR(20))
from NF_COMPRA A
join CONTABIL_LANCAMENTOS B on
	B.FORMULARIO_ORIGEM = A.FORMULARIO_ORIGEM and 
	B.tab_master_origem = A.TAB_MASTER_ORIGEM and
	B.reg_master_origem = A.NF_COMPRA 
where 
	A.CHAVE_NFE = '35190403227823000142550020000093511001162887'
-- qualquer valor diferente de ZERO deve dar mensagem de restrição


SELECT TOP 1 'NF COMPRA: '+ CAST(C.NF_COMPRA AS VARCHAR (20)) +' JÁ ESTÁ CONTABILIZADA: '+CAST(B.CONTABILIDADE AS VARCHAR(20))
from NF_COMPRA A
join CONTABIL_LANCAMENTOS B on
	B.FORMULARIO_ORIGEM = A.FORMULARIO_ORIGEM and 
	B.TAB_MASTER_ORIGEM = A.TAB_MASTER_ORIGEM and
	B.REG_MASTER_ORIGEM = A.NF_COMPRA 
join FP_NOTAS_RECEBIDAS_DETALHES C on
	C.NF_COMPRA = A.NF_COMPRA
where
	C.NOTA_RECEBIDA =:NOTA_RECEBIDA



SELECT TOP 1 'NF COMPRA: '+ CAST(A.NF_COMPRA AS VARCHAR (20)) +' JÁ ESTÁ CONTABILIZADA: '+CAST(B.CONTABILIDADE AS VARCHAR(20))
from NF_COMPRA A
join CONTABIL_LANCAMENTOS B on
	B.FORMULARIO_ORIGEM = A.FORMULARIO_ORIGEM and 
	B.TAB_MASTER_ORIGEM = A.TAB_MASTER_ORIGEM and
	B.REG_MASTER_ORIGEM = A.NF_COMPRA 
join FP_NOTAS_RECEBIDAS_DETALHES C on
	C.NF_COMPRA = A.NF_COMPRA
join FP_NOTAS_RECEBIDAS D on
	D.NOTA_RECEBIDA = C.NOTA_RECEBIDA
WHERE
	C.NOTA_RECEBIDA =12726 AND
	D.DATA_PROCESSADO IS NOT NULL 

	
	
--NOTA RECEBIDA	12726 / 14098
--NF COMPRA		1055997 / 1055997
--FORMULARIO_OR 48
--TAB_MASTER_OR	41
--REG_MASTER_OR 1024329 



--------------------------------------------------------------------------------------------

SELECT 'NAO E PERMITIDO EDITAR REGISTRO JA PROCESSADO'
FROM FP_NOTAS_RECEBIDAS
WHERE NOTA_RECEBIDA = :NOTA_RECEBIDA AND 
      DATA_PROCESSADO IS NOT NULL



sp_helptext 'farmaponte.SP_VALIDA_NOTA_DESPACHO' 



select STUFF((    
             SELECT ',' +  X.tab 
              FROM (    

                SELECT 'A' as tab
				union
				select 'b'
       
              )X ORDER BY X.tab    
                FOR XML PATH('')    
          ),1,1,'') 



SELECT 'NF COMPRA: ' + SUBSTRING(STUFF((    
             SELECT ', ' +  X.TAB 
              FROM (    
               
			SELECT DISTINCT CAST(A.NF_COMPRA AS VARCHAR (20)) as tab 
			FROM NF_COMPRA A
			JOIN CONTABIL_LANCAMENTOS B ON
				B.FORMULARIO_ORIGEM = A.FORMULARIO_ORIGEM AND 
				B.TAB_MASTER_ORIGEM = A.TAB_MASTER_ORIGEM AND
				B.REG_MASTER_ORIGEM = A.NF_COMPRA 
			JOIN FP_NOTAS_RECEBIDAS_DETALHES C ON
				C.NF_COMPRA = A.NF_COMPRA
			JOIN FP_NOTAS_RECEBIDAS D ON
				D.NOTA_RECEBIDA = C.NOTA_RECEBIDA
			WHERE
				C.NOTA_RECEBIDA = :NOTA_RECEBIDA
				D.DATA_PROCESSADO IS NOT NULL 
                          
              )X ORDER BY X.TAB    
                FOR XML PATH('')    
          ),1,1,''), 1,50) + '... JÁ ESTÃO CONTABILIZADAS.'


--------------------------------------------------------------------------------------------------------
		  
SELECT TOP 1 'NOTA FISCAL JÁ CONTABILIZADA - '+ CAST(B.CONTABILIDADE AS VARCHAR(20))
FROM NF_COMPRA A
JOIN CONTABIL_LANCAMENTOS B ON
    B.FORMULARIO_ORIGEM = A.FORMULARIO_ORIGEM AND 
    B.TAB_MASTER_ORIGEM = A.TAB_MASTER_ORIGEM AND
    B.REG_MASTER_ORIGEM = A.NF_COMPRA 
WHERE 
    A.CHAVE_NFE = :CHAVE_NFE





